### ISSUE TITLE
if viewing a shared screen while not logged in, persona (browserid) login button doesn't work

### ISSUE THREAD

**Issue by operatorjen** [mozilla/napkin#29]
is the share screen supposed to be accessible by a user that isn't logged in, or only people who are logged in?

![screenshot](http://f.cl.ly/items/420Z311t0c12403f2D2b/Napkin%20-%20The%20Rapid%20Web%20Prototyping%20Tool-1.jpg)

**Comment by karthikv** [comment]
The share screen page is accessible by everyone and has no sign in button in that area. The screenshot you posted is actually that of a not found page rather than a share screen page.

**Comment by operatorjen** [comment]
ahhh hmm yeah i just tested again.. works this time.. must have been pointing to one of the old screens before the merge yesterday. will close
