### ISSUE TITLE
Dragging an element back to the sidebar should delete it

### ISSUE THREAD

**Issue by fwenzel** [mozilla/napkin#36]
Might want to make the sidebar a huge trash can when dragging an item. Huge drag targets for the win.

**Comment by karthikv** [comment]
Elements are not draggable right now; they are only sortable within their parent container. Do you think this is important enough for me to add in the extra drag logic? I thought the "delete" button when you focus on an element was pretty clear, but perhaps not. Let me know and I'll get on it.

**Comment by fwenzel** [comment]
Hm nah, this is not that important to me. If you want, we can keep this issue around for a future feature, or close it out and say this is how it works for now and dragging to remove is just not supported. @ednapiranha what say you?

**Comment by operatorjen** [comment]
I'd say we close it for now and see how users feel. If it becomes a big issue for the majority we can reopen as a new bug.

**Comment by karthikv** [comment]
All right, I'll close the issue for now. We can address it if it comes up.
