### ISSUE TITLE
Share screen should open in a new window

### ISSUE THREAD

**Issue by operatorjen** [mozilla/napkin#56]

**Comment by karthikv** [comment]
Why do you say this? I tend to like giving the user control of whether he/she wants to open the share screen in a new tab, in a new window, or on the same page.

**Comment by operatorjen** [comment]
opening in the current screen assumes that the user will right click to open to a new window when that may not necessarily be the case. so to be safe, it's better to just have a lazy target to a new window and not lose context of the current working state.

**Comment by karthikv** [comment]
> opening in the current screen assumes that the user will right click to open to a new window when that may not necessarily be the case.

I don't understand this point. I often open a share screen in the same window and just hit the back button; it's less obtrusive than a new window. In fact, I've never kept a share screen open in a different tab or window. If the user prefers a new window, they can always right click and make one.

I'm also not sure how the user would ever lose context of the working state. The share screen nearly mirrors the working copy except for the added interactive functionality, so it's hard to see how any context is lost.

**Comment by karthikv** [comment]
Closing this issue because I'm largely against forcing something to open in a new window. Reopen if you feel you have a case.
