### ISSUE TITLE
Adding an element sometimes displays more than one

### ISSUE THREAD

**Issue by operatorjen** [mozilla/napkin#58]
When adding a new paragraph element or heading, I sometimes see two appear. Once refreshing, only the last one appears (I edited both before refresh and noticed that it just took the text from the last one - might be a clue?)

**Comment by karthikv** [comment]
What browser are you using? This has never happened to me in Chrome.

**Comment by karthikv** [comment]
Also, if you happen to reproduce it, could you look at the console and see if there are any issues? I just experienced something similar to this due to some templates not being correctly loaded. I'm guessing this is simply because the server was restarting when I was making changes.

**Comment by operatorjen** [comment]
hmm i'm not going to trust firefox nightly for now but seems to be ok in chrome (for now). will close issue unless i can repeat again.
