### ISSUE TITLE
uses the Persona sign in button as a sign out button. This is confusing.

### ISSUE THREAD

**Issue by graingert** [mozilla/napkin#76]
The offending article:
<img src="http://i.imgur.com/EyLx7.png" />

The Persona sign in button will be used across the web to mean exactly that: To sign in. Using it as a sign out button dilutes the Persona brand.

Not only this the Persona sign in button is naturally a call to action, and using a call to action for a sign out action is generally a bad idea.

Also the button (area where the sign in action is initiated) does not change significantly between signed in and signed out state. As such when I first used the site I signed in, and then signed out immediately afterwards because I assumed Persona had broken in some way.

This should be the user's gravatar/libravatar followed by their account.

**Comment by karthikv** [comment]
This has been addressed in the pull request above.
