### ISSUE TITLE
Greyed out filter on landing page takes a while to load. (FOUC on landing.)

### ISSUE THREAD

**Issue by graingert** [mozilla/napkin#78]
Greyed out filter on landing page takes a while to load. (FOUC on landing.)

In order to draw attention to the sign in button the page is greyed out. This greying out filter is, however, only applied after the page has loaded thus causing a FOUC.

**Comment by karthikv** [comment]
Ah, yes, this does happen. I'm planning to completely change the landing page by getting rid of the overlay and adding some more informative content. Until then, though, I'll keep this issue open in case that plan changes.

**Comment by karthikv** [comment]
This has been taken care of in the pull request above.
