### ISSUE TITLE
Reduce max screen size of app to 960px

### ISSUE THREAD

**Issue by operatorjen** [mozilla/napkin#81]
Reduce the screen width and let everything adjust accordingly. It's a bit too wide for most resolutions as not everyone is on a really wide screen (e.g. might be working on a laptop).

I'd probably think of moving the Github link to a non-conventional one (just in the side nav as a small link or something) so we don't have to worry about it blocking anything

**Comment by karthikv** [comment]
Taken care of (at least preliminarily) in the pull request above.
