### ISSUE TITLE
Changing column layout of a row deletes its contents

### ISSUE THREAD

**Issue by fwenzel** [mozilla/napkin#83]
@morgamic  just hit this snag:

Create a row with, say, three columns and put some content in.

Then change the layout of that row.

It'll delete the content of the entire row. Ouch.

We should probably warn, or disallow changing the layout if we can't reasonably salvage the content?

**Comment by karthikv** [comment]
Just talked this over and it looks like Napkin already takes care of this. Perhaps this only happens in certain cases? I'll keep my eye on it. Closing for now.
