### ISSUE TITLE
Linking to other Screens

### ISSUE THREAD

**Issue by stackmagic** [mozilla/napkin#91]
Hi there

I just tried napkin and wanted to build a little base structure of a site which includes a nav bar and links between pages. Now I can add screen links to a navigation and let a screen link to itself but not to another screen, I always get a note saying "Element's screen must correspond to a real screen.". At times I get the same message on the Screen link on the menu on the left and can't even drag the Screne link onto the page.

This napkin thing looks like an awesome tool. If it works, I'd love to try it a bit more and maybe actually use it.

Cheers

Edit: I tried on Linux w/ chromium-20 and firefox-15

**Comment by operatorjen** [comment]
Hey, should be fixed now - let me know if you run into a similar problem again :)
